export { ApiClient, HermesApiError, apiClient, createApiError, isApiError, getErrorDetail } from './apiClient';
export type { RequestOptions } from './apiClient';

export * from './sessionApi';
export * from './skillsApi';
export * from './cronJobsApi';
export * from './settingsApi';
export * from './hermesChat';
export * from './analyticsApi';
export * from './statusApi';
export * from './monitorApi';
export * from './memoryApi';
export * from './platformApi';
export * from './filesApi';
export * from './mcpApi';
export * from './updateApi';
export * from './toolsApi';
export * from './eventService';

import * as _sessionApi from './sessionApi';
import * as _skillsApi from './skillsApi';
import * as _cronJobsApi from './cronJobsApi';
import * as _settingsApi from './settingsApi';
import * as _statusApi from './statusApi';
import * as _analyticsApi from './analyticsApi';
import * as _monitorApi from './monitorApi';
import * as _memoryApi from './memoryApi';
import * as _platformApi from './platformApi';
import * as _filesApi from './filesApi';
import * as _mcpApi from './mcpApi';
import * as _toolsApi from './toolsApi';

export const sessionApi = _sessionApi;
export const skillsApi = _skillsApi;
export const cronJobsApi = _cronJobsApi;
export const settingsApi = _settingsApi;
export const statusApi = _statusApi;
export const analyticsApi = _analyticsApi;
export const monitorApi = _monitorApi;
export const memoryApi = _memoryApi;
export const platformApi = _platformApi;
export const filesApi = _filesApi;
export const mcpApi = _mcpApi;
export const toolsApi = _toolsApi;
